
services:
  ampsvelte:
    image: ampsvelte:0.1.0
    build: .
    networks:
      - ampsvelte
    ports:
      - 4588:80

networks:
  ampsvelte:
    
    # environment: 
    #   - HOST=192.168.0.91
    #   - PORT=4588